### ISSUE TITLE
[refactor]  UX 개선 - 태그를 입력 하면 스크롤을 해야 추가된 태그들을 확인할 수 있음

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [YAPP-Github/21st-Web-Team-2-FE#159]
## 💡 목적
![image](https://user-images.githubusercontent.com/45627868/220659896-c5e9aa0c-598a-4d2b-bca3-199386acc743.png)
- 태그 입력 후 Enter 를 누르면 태그가 잘 나오지만, 사용자가 스크롤을 내려야 확인할 수 있음
  =>  UX 를 개선하기 위해 Enter 치면 자동으로 내려가던가 처음부터 태그가 나오도록 UI 개선하면 좋을듯! 
- 그리고 태그 박스와 수정 버튼 border-top 이 겹쳐져서 띄우는 것도 좋아보임

## 📝 Todo
- [ ] ux 개선

**Comment by KIMSEUNGGYU** [comment]
@hwookim 님 의견은 어떤가요?

**Comment by hwookim** [comment]
애초에 화면이 작으면 태그 맨 밑도 처리하지 못하는군요...!
개선이 필요해보입니다.

하단에 충분한 공간을 주는 것과 더불어 말씀하신 약간의 스크롤 다운이 있으면 좋을 것 같아요.

**Comment by hwookim** [comment]
이거 코드를 확인해보니까 원래는 맨 밑에 공간 남겨두려고 태그도 추가했는데
css 설정을 잘못해서 이상한 방향으로 가고 있었네요... 😅 
수정해서 pr 올리겠습니다!
