### ISSUE TITLE
[feat] 메인페이지 글쓰기 버튼 구현

### ISSUE THREAD

**Issue by hwookim** [YAPP-Github/21st-Web-Team-2-FE#34]
## 💡 목적

<img width="377" alt="스크린샷 2023-01-07 오후 2 54 45" src="https://user-images.githubusercontent.com/45786387/211133515-efee762c-9e95-42af-91ba-d610b863ab77.png">
<img width="64" alt="스크린샷 2023-01-07 오후 2 54 57" src="https://user-images.githubusercontent.com/45786387/211133520-f2cee766-b649-441d-9d0c-99590828da2b.png">

## 📝 Todo

- [x] 긴 버튼 구현
- [x] Fab 버튼 구현
- [x] 긴 글쓰기 버튼 화면에서 사라지면 Fab 버튼 렌더링

**Comment by KIMSEUNGGYU** [comment]
@hwookim 님
- 긴 버튼 형태 와 Fab 버튼 형태 UI 구현 완료하였습니다!
- Fab 버튼의 경우 visible props 로 hidden 또는 visible 하게 사용할 수 있도록 하였습니다
