### ISSUE TITLE
프로젝트 테스팅 라이브러리 추가

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [YAPP-Github/21st-Web-Team-2-FE#4]
## 💡 목적
- 프로젝트 테스팅을 할 수 있는 테스팅 라이브러리를 추가하자

## 📝 Todo
- [x] 테스팅 라이브러리 추가하기
  - [x]  jest 및 react-testing-library 추가
  - [x] cypress 추가

## ‼️ 주의 사항
- ‼️ github PR 요청시 리뷰어 하나 하나 달아줘야 하는데(사람이 많아서) 찾기가 불편합니다. 
   그래서 [`codeowners` 속성을 주려고 하는데 의견 부탁드립니다.](https://goodgid.github.io/Github-CODEOWNERS/)
- 해당 branch 에 들어가서 ESLint 설정이 제대로 동작하는지 확인 바랍니다.

**Comment by hwookim** [comment]
feature명은 순서가 아니라 이슈 번호로 가져가는 편이 더 좋을 것 같습니다!
그래야 close할 때도 일원화되어서 관리가 수월할 것 같아요.

추가적으로 되도록이면 한 번에 하나의 작업만 하면 좋겠습니다.
테스팅 라이브러리를 추가하는 것과, codeowners를 추가하는 건 너무 다른 일이지 않나요?

**Comment by KIMSEUNGGYU** [comment]
> feature명은 순서가 아니라 이슈 번호로 가져가는 편이 더 좋을 것 같습니다! 그래야 close할 때도 일원화되어서 관리가 수월할 것 같아요.
- 좋은거 같아요!! 
그럼 이번 작업부터 할까요?? 
=> 이번 작업부터 하면 현재 브랜치에서 `feature-004` 로 분기해서 처리하고 main 에 merge 할 예정입니다. 


> 추가적으로 되도록이면 한 번에 하나의 작업만 하면 좋겠습니다. 테스팅 라이브러리를 추가하는 것과, codeowners를 추가하는 건 너무 다른 일이지 않나요? 리뷰어 자동 지정 로직 추가하는 건 좋습니다!
- 음.. 저도 작업할 때 이렇게 분리하는걸 좋아하는데 setting 으로 그냥 하나로 묶고 싶어서 생각했습니다. 
  근데, 따로 작업하는걸 추천하시나요??

**Comment by hwookim** [comment]
코드 오너 추가 빠르게 적용시키고 현재 이슈랑 스토리북 이슈에 반영되도록 해도 괜찮지 않을까요?
빨리 끝낼 수 있는 것 먼저 끝내는 편이 좋다고는 생각합니다!
