### ISSUE TITLE
[feat] 기본 이미지 추가

### ISSUE THREAD

**Issue by hwookim** [YAPP-Github/21st-Web-Team-2-FE#73]
## 💡 목적

![image](https://user-images.githubusercontent.com/45786387/216766841-e8e9aeb1-a394-43a0-88fe-157d167fbd67.png)
![image](https://user-images.githubusercontent.com/45786387/216766850-e1e63961-6eea-45e0-865d-b77b44f3fd0c.png)
![image](https://user-images.githubusercontent.com/45786387/216766860-63f271c3-54a8-48a0-81f2-c7e4c930f20e.png)

## 📝 Todo

- [ ] 개발자, 디자이너, 기획자 별 기본 이미지 추가

**Comment by KIMSEUNGGYU** [comment]
해당 부분 제가 온보딩 구현하면서 작업해서 없애도 괜찮을거 같아요
